### ISSUE TITLE
Is the data private?How can I get it if it is publicly available?

### ISSUE THREAD

**Issue by xyfxdweixiaofei** [chennnnnyize/BayesianRenewablesGAN#1]

**Comment by chennnnnyize** [comment]
Hi, Could you please check the data listed in my other repo, GAN for renewables scenario generation? I use similar data for this repo, and will upload it shortly. Thanks!

https://github.com/chennnnnyize/Renewables_Scenario_Gen_GAN

**Comment by xyfxdweixiaofei** [comment]
thanks very much you to reply！I have a a question .for  GAN for renewables scenario generation, how to implementation single Time-Series Scenario generation ,whice is remove labels y?

**Comment by chennnnnyize** [comment]
Hi, basically there are two solutions based on the current version of code I uploaded. Firstly, you can give random conditional label for y. In this sense, z and y are working in the same fashion. Another approach you need revise the code a little bit. For instance, you can delete all the concatenation part in the code, so that the network only use z as input for training and generation.

**Comment by xyfxdweixiaofei** [comment]
hi,thank you for your patient reply.wish you have better results and achievements.------------------ 原始邮件 ------------------
发件人: "Yize Chen"<notifications@github.com>
发送时间: 2019年5月21日(星期二) 中午12:18
收件人: "chennnnnyize/BayesianRenewablesGAN"<BayesianRenewablesGAN@noreply.github.com>;
抄送: "xyfxdweixiaofei"<1932243823@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chennnnnyize/BayesianRenewablesGAN] Is the data private?How canI get it if it is publicly available? (#1)



Hi, basically there are two solutions based on the current version of code I uploaded. Firstly, you can give random conditional label for y. In this sense, z and y are working in the same fashion. Another approach you need revise the code a little bit. For instance, you can delete all the concatenation part in the code, so that the network only use z as input for training and generation.
 
&mdash;

**Comment by chennnnnyize** [comment]
You are welcome! Good luck with your trials and let me know if you have any furthur questions.
